basePath: /
definitions:
  ErrorResponse:
    properties:
      error:
        example: Error message
        type: string
    type: object
  File:
    properties:
      group:
        type: string
      lastModified:
        type: string
      owner:
        type: string
      path:
        type: string
      permissions:
        description: swagger:strfmt string
        type: string
      size:
        type: integer
    type: object
  FileRequest:
    properties:
      content:
        example: file contents here
        type: string
      isDirectory:
        example: false
        type: boolean
      permissions:
        example: "0644"
        type: string
    type: object
  PortMonitorRequest:
    properties:
      callback:
        description: URL to call when a new port is detected
        example: http://localhost:3000/callback
        type: string
    type: object
  ProcessKillRequest:
    properties:
      signal:
        example: SIGTERM
        type: string
    type: object
  ProcessRequest:
    properties:
      command:
        example: ls -la
        type: string
      name:
        example: my-process
        type: string
      streamLogs:
        example: true
        type: boolean
      timeout:
        example: 30
        type: integer
      waitForCompletion:
        example: false
        type: boolean
      waitForPorts:
        example:
        - 3000
        - 8080
        items:
          type: integer
        type: array
      workingDir:
        example: /home/user
        type: string
    required:
    - command
    type: object
  ProcessResponse:
    properties:
      command:
        example: ls -la
        type: string
      completedAt:
        example: Wed, 01 Jan 2023 12:01:00 GMT
        type: string
      exitCode:
        example: 0
        type: integer
      name:
        example: my-process
        type: string
      pid:
        example: "1234"
        type: string
      startedAt:
        example: Wed, 01 Jan 2023 12:00:00 GMT
        type: string
      status:
        example: running
        type: string
      workingDir:
        example: /home/user
        type: string
    type: object
  SuccessResponse:
    properties:
      message:
        example: File created successfully
        type: string
      path:
        example: /path/to/file
        type: string
    type: object
  Directory:
    properties:
      files:
        items:
          $ref: '#/definitions/File'
        type: array
      path:
        type: string
      subdirectories:
        description: '@name Subdirectories'
        items:
          $ref: '#/definitions/Directory'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for manipulating filesystem, processes and network.
  title: Sandbox API
  version: 0.0.1-preview
paths:
  /filesystem/{path}:
    delete:
      consumes:
      - application/json
      description: Delete a file or directory
      parameters:
      - description: File or directory path
        in: path
        name: path
        required: true
        type: string
      - description: Delete directory recursively
        in: query
        name: recursive
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            $ref: '#/definitions/SuccessResponse'
        "404":
          description: File or directory not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Delete file or directory
      tags:
      - filesystem
    get:
      consumes:
      - application/json
      description: Get content of a file or listing of a directory
      parameters:
      - description: File or directory path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Directory listing
          schema:
            $ref: '#/definitions/Directory'
        "404":
          description: File or directory not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get file or directory information
      tags:
      - filesystem
    put:
      consumes:
      - application/json
      description: Create or update a file or directory
      parameters:
      - description: File or directory path
        in: path
        name: path
        required: true
        type: string
      - description: File or directory information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/FileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Create or update file or directory
      tags:
      - filesystem
  /network/process/{pid}/monitor:
    delete:
      consumes:
      - application/json
      description: Stop monitoring for new ports opened by a process
      parameters:
      - description: Process ID
        in: path
        name: pid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Object containing PID and success message
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid process ID
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Stop monitoring ports for a process
      tags:
      - network
    post:
      consumes:
      - application/json
      description: Start monitoring for new ports opened by a process
      parameters:
      - description: Process ID
        in: path
        name: pid
        required: true
        type: integer
      - description: Port monitor configuration
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/PortMonitorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Object containing PID and success message
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Start monitoring ports for a process
      tags:
      - network
  /network/process/{pid}/ports:
    get:
      consumes:
      - application/json
      description: Get a list of all open ports for a process
      parameters:
      - description: Process ID
        in: path
        name: pid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Object containing PID and array of network.PortInfo
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid process ID
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get open ports for a process
      tags:
      - network
  /process:
    get:
      consumes:
      - application/json
      description: Get a list of all running and completed processes
      produces:
      - application/json
      responses:
        "200":
          description: Process list
          schema:
            items:
              $ref: '#/definitions/ProcessResponse'
            type: array
      summary: List all processes
      tags:
      - process
    post:
      consumes:
      - application/json
      description: Execute a command and return process information
      parameters:
      - description: Process execution request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ProcessRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Process information
          schema:
            $ref: '#/definitions/ProcessResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Execute a command
      tags:
      - process
  /process/{identifier}:
    delete:
      consumes:
      - application/json
      description: Gracefully stop a running process
      parameters:
      - description: Process identifier (PID or name)
        in: path
        name: identifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Process stopped
          schema:
            $ref: '#/definitions/SuccessResponse'
        "404":
          description: Process not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Stop a process
      tags:
      - process
    get:
      consumes:
      - application/json
      description: Get information about a process by its PID or name
      parameters:
      - description: Process identifier (PID or name)
        in: path
        name: identifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Process information
          schema:
            $ref: '#/definitions/ProcessResponse'
        "404":
          description: Process not found
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get process by identifier
      tags:
      - process
  /process/{identifier}/kill:
    delete:
      consumes:
      - application/json
      description: Forcefully kill a running process
      parameters:
      - description: Process identifier (PID or name)
        in: path
        name: identifier
        required: true
        type: string
      - description: Kill options
        in: body
        name: request
        schema:
          $ref: '#/definitions/ProcessKillRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Process killed
          schema:
            $ref: '#/definitions/SuccessResponse'
        "404":
          description: Process not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Kill a process
      tags:
      - process
  /process/{identifier}/logs:
    get:
      consumes:
      - application/json
      description: Get the stdout and stderr output of a process
      parameters:
      - description: Process identifier (PID or name)
        in: path
        name: identifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Process logs
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Process not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get process logs
      tags:
      - process
swagger: "2.0"
