name: UVM Build and Push
on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      uvm:
        description: "UVM to import"
      all:
        description: "Import all UVM"
        type: boolean
        required: false
        default: false
      workspace:
        description: "Workspace to use"
        type: string
        required: false
        default: ""

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      uvm: ${{ steps.retrieve-uvm.outputs.uvm }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last 2 commits to compare changes
      - name: Retrieve uvm
        id: retrieve-uvm
        shell: bash
        run: |
          if [[ ! -z "${{ inputs.uvm }}" ]]; then
            echo "uvm=[\"${{ inputs.uvm }}\"]" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get list of all UVM files
          all_uvm=$(tree -J -L 1 | jq -c '.[0].contents | map(select(.name | startswith("Dockerfile.")) | .name | ltrimstr("Dockerfile."))')

          # Filter UVM based on changes
          changed_uvm=()

          if [[ "${{ inputs.all }}" == "true" ]]; then
            echo "Importing all UVM"
            echo "uvm=$all_uvm" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check if there are changes in uvm-api
          if git diff --name-only HEAD^ HEAD | grep -q "uvm-api/"; then
            echo "Changes detected in uvm-api, including all UVM"
            echo "uvm=$all_uvm" >> $GITHUB_OUTPUT
            exit 0
          else
            for uvm in $(echo $all_uvm | jq -r '.[]'); do
              if git diff --name-only HEAD^ HEAD | grep -q "Dockerfile.${uvm}"; then
                changed_uvm+=("$uvm")
              fi
            done
          fi

          # Convert array to JSON array
          if [ ${#changed_uvm[@]} -eq 0 ]; then
            echo "No UVM with changes found"
            echo "uvm=[]" >> $GITHUB_OUTPUT
          else
            # Create a properly formatted JSON array
            uvm_json="["
            for uvm in "${changed_uvm[@]}"; do
              if [ "$uvm_json" != "[" ]; then
                uvm_json="$uvm_json,"
              fi
              uvm_json="$uvm_json\"$uvm\""
            done
            uvm_json="$uvm_json]"
            echo "uvm=$uvm_json" >> $GITHUB_OUTPUT
          fi
  publish:
    runs-on: ubuntu-latest
    if: needs.generate-matrix.outputs.uvm != '[]'
    environment: |-
      ${{
        github.ref_name == 'main' && 'prod'
      || github.ref_name == 'develop' && 'dev'
      || 'dev'
      }}
    env:
      BL_API_URL: ${{ vars.BL_API_URL }}
      BL_ADMIN_USERNAME: ${{ vars.BL_ADMIN_USERNAME }}
      BL_ADMIN_PASSWORD: ${{ secrets.BL_ADMIN_PASSWORD }}
      UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
      UKC_METRO: ${{ vars.UKC_METRO }}
      BL_ENV: ${{ vars.BL_ENV }}
    needs:
      - generate-matrix
    strategy:
      matrix:
        uvm: ${{ fromJson(needs.generate-matrix.outputs.uvm )}}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo uvm
        run: |
          echo "UVM: ${{ matrix.uvm }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: "1.23.3"
      - name: Setup binary folder
        run: |
          echo "$PWD/bin" >> $GITHUB_PATH
      - name: Build and push
        env:
          BL_WORKSPACE: ${{ inputs.workspace }}
          TAG: ${{ github.run_id }}
        run: |
          sh build.sh
